[package]
name = "capabilities_old"
version = "0.1.0"
authors = ["Inanna Malick <inanna@recursion.wtf>"]
edition = "2018"

[dependencies]
library_old = { path = "../../deps/library_old" }
futures = "0.1"